---
name: Math-Round-Var
version: 0.03
author: []
abstract: Variations on rounding.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
provides:
  Math::Round::Var:
    file: lib/Math/Round/Var.pm
    version: 0.03
  Math::Round::Var::Fake:
    file: lib/Math/Round/Var.pm
  Math::Round::Var::Float:
    file: lib/Math/Round/Var.pm
  Math::Round::Var::Fraction:
    file: lib/Math/Round/Var.pm
generated_by: Module::Build version 0.28
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
